---
abstract: 'super light TAL for Perl!'
author:
  - 'Lars Balker <lars@balker.dk>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Petal-Tiny
resources:
  homepage: https://github.com/lbalker/petal-tiny
  repository: https://github.com/lbalker/petal-tiny.git
version: '1.13'
